<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Gurux.Common" Version="8.4.2503.602" />
    <PackageReference Include="Gurux.DLMS" Version="9.0.2508.2201" />
    <PackageReference Include="Gurux.MQTT" Version="8.1.2503.1301" />
    <PackageReference Include="Gurux.Net" Version="8.4.2503.1001" />
	<PackageReference Include="Gurux.Serial" Version="8.4.2503.603" />
	<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
    <PackageReference Include="nats.net" Version="2.6.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DlmsMqttExecutor.Application\DlmsMqttExecutor.Application.csproj" />
    <ProjectReference Include="..\DlmsMqttExecutor.Domain\DlmsMqttExecutor.Domain.csproj" />
  </ItemGroup>

</Project>
