<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dotnetenv" Version="3.1.1" />
    <PackageReference Include="serilog" Version="4.3.0" />
    <PackageReference Include="serilog.aspnetcore" Version="9.0.0" />
	<PackageReference Include="Grpc.AspNetCore" Version="2.64.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DlmsMqttClientGrpc.Application\DlmsMqttClientGrpc.Application.csproj" />
    <ProjectReference Include="..\DlmsMqttClientGrpc.Infrastructure\DlmsMqttClientGrpc.Infrastructure.csproj" />
    <ProjectReference Include="..\DlmsMqttClientGrpc.Protos\DlmsMqttClientGrpc.Protos.csproj" />
  </ItemGroup>

</Project>
